---
driver:
  name: vcenter
  vcenter_username: <%= ENV['VCENTER_USER'] || "administrator@vsphere.local" %>
  vcenter_password: <%= ENV['VCENTER_PASSWORD'] || "Good4bye!" %>
  vcenter_host:  "10.0.0.2"
  vcenter_disable_ssl_verify: true

provisioner:
  name: chef_zero
  sudo_command: sudo

verifier:
  name: inspec

platforms:
  - name: ubuntu-1604
    transport:
      username: admini
      password: admini
    driver_config:
      targethost: 172.16.20.41
      template: template-ubuntu1604
      datacenter: "Datacenter"
      resource_pool: "testkitchen"

  - name: centos-7
    transport:
      username: root
      password: admini
    driver_config:
      targethost: 172.16.20.41
      template: template-centos7
      datacenter: "Datacenter"
      resource_pool: "testkitchen"

suites:
- name: default
  run_list:
  - recipe[vim::default]
